function [Wave_Data] = RDIWH_process_waves(path, Log9_file) 
%
%  Reads in the .txt file for OB27 that is generated by Wavesmon.
%  The text file must be in format 9 from Wavesmon.
%
%   Input   - filename = the file name of the txt file e.g. OB27_process_waves('waves-2021-sep-2021-nov_000_000_LOG9.TXT').
%   Output  - H_s = Significant wave height
%           - T_p = Mean wave period 
%           - M_d = mean wave direction in degrees CW from north
%           - time = time in Matlab's datetime format. May want to check time zone 
%           when processing with Wavesmon.
%
% 
file=append(path,'\', Log9_file);
fileID = fopen(file);

[C] = textscan(fileID, '%d, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f %*[^\n]');  

fclose(fileID);

year = C{1,2};
month = C{1,3};
day = C{1,4};
hour = C{1,5};
min = C{1,6};
sec = C{1,7};

time= datetime([year+2000 month day hour min sec]); %adding 2000 to make YY into YYYY format

H_s = C{1,9};
T_p = C{1,10};
M_d = C{1,11};

Wave_Data.Hs=H_s;
Wave_Data.Tp=T_p;
Wave_Data.Md=M_d;
Wave_Data.time=time;

clear ans C day fileID filename hour min month sec year

end

